use :
	chmod +x BaStick.bash

clean :
	rm -f protalign
	rm -f protbank
	rm -f final.*
	rm -f fichiertempotranseteval
	rm -f fichiertempofpkm.*
	rm -f fichiertempoofpkm
	rm -f ensembledesprotetventralavecdomencomm
	rm -f *.domainsolo
	rm -f *.domainsolo.sort
	rm -f *.domainencommun
	rm -f *.domain
	rm -f *.seqorf
	rm -f *.aalignes
	rm -f *.orfpossibleavectaille
	rm -f *.que
	rm -f *.queaa
	rm -f *.resultatsixpackfastq
	rm -f *.tailleorf
	rm -f *.tailleorfaa
	rm -f *.tailleorfaacount
	rm -f *.tailleorfaacountrep
	rm -f *.tailleorfaacounttaille
	rm -f *.menfou
	rm -f *.resultatsixpack
	rm -f *.resultat
	rm -f *.seq
	rm -f *.lesbonsventros
	rm -f *.FPKM
	rm -f *.sort
	rm -f *.sort2
	rm -f *.sort2point
	rm -f *.allventronom
	rm -f *.lesbonsventrovirgule
	rm -f *.lesbonsventro
	rm -f *.FPKMtranscrits
	rm -f *.domainsort
	rm -f *.1
	rm -f *.2
	rm -f *.3
	rm -f *.psq
	rm -f *.pin
	rm -f *.phr
	rm -f *.pdb
	rm -f *.pto
	rm -f *.ptf
	rm -f *.pot
	rm -f *.nsq
	rm -f *.nin
	rm -f *.nhr
	rm -f *.ndb
	rm -f *.nto	
	rm -f *.ntf
	rm -f *.not
	rm -f *.blast 
	rm -f *.etape1bash 
	rm -f blast.*
	rm -f *.fasta
	rm -f *.fa
	rm -f *.fq 
	rm -f *.csv	
	

