clean :
#~ 	rm protalign
#~ 	rm protbank
#~ 	rm fichiertempotranseteval
#~ 	rm ensembledesprotetventralavecdomencomm
	rm *.domainsolo
	rm *.domainsolo.sort
	rm *.domainencommun
	rm *.domain
	rm *.seqorf
	rm *.aalignes
	rm *.orfpossibleavectaille
	rm *.que
	rm *.queaa
	rm *.resultatsixpackfastq
	rm *.tailleorf
	rm *.tailleorfaa
	rm *.tailleorfaacount
	rm *.tailleorfaacountrep
	rm *.tailleorfaacounttaille
	rm *.menfou
	rm *.resultatsixpack
	rm *.resultat
	rm *.seq
	rm *.lesbonsventros
	rm *.FPKM
	rm *.sort
	rm *.sort2
	rm *.sort2point
	rm *.allventronom
	rm *.lesbonsventrovirgule
	rm *.lesbonsventro
	rm *.FPKMtranscrits
	rm *.domainsort
	rm *.1
	rm *.2
	rm *.3
	rm *.psq
	rm *.pin
	rm *.phr
	rm *.pdb
	rm *.pto
	rm *.ptf
	rm *.pot
	rm *.nsq
	rm *.nin
	rm *.nhr
	rm *.ndb
	rm *.nto
	rm *.ntf
	rm *.not
	rm *.blast 
	rm *.etape1bash 
	rm blast.*
	rm *.fasta
	rm *.fa
	rm *.fq 
	rm *.csv
